version: '3.8'

services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    restart: always
    hostname: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      logging-network:
        aliases:
          - loki
        ipv4_address: 172.23.0.200
    deploy:
      resources:
        limits:
          memory: 100M

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    restart: always
    volumes:
      - /opt/auto-deploy/logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - logging-network 
    deploy:
      resources:
        limits:
          memory: 50M

  grafana:
    image: logs-web
    container_name: grafana
    pull_policy: never
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs-web.entrypoints=http"
      - "traefik.http.routers.logs-web.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.entrypoints=https"
      - "traefik.http.routers.logs-web-secure.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.tls=true"
      - "traefik.http.routers.logs-web-secure.service=logs-web-secure"
      - "traefik.http.services.logs-web-secure.loadbalancer.server.port=3000"
      - "traefik.docker.network=external-sol-apis"
    depends_on:
      - loki
    networks:
      - logging-network
      - external-sol-apis
    deploy:
      resources:
        limits:
          memory: 100M

volumes:
  grafana-data:

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
