version: '3.8'

services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    restart: unless-stopped
    hostname: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      logging-network:
        aliases:
          - loki
        ipv4_address: 172.23.0.200
    deploy:
      resources:
        limits:
          memory: 100M

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /opt/auto-deploy/logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - logging-network 
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=promtail,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 50M
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=prometheus,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50M 

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    command:
      - "--storage_driver=statsd"
      - "--disable_metrics=percpu,sched,tcp,udp,disk"
      - "--disable_root_cgroup_stats=true"
    networks:
      - logging-network
    deploy:
      resources:
        limits:
          memory: 25M 

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - logging-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 15M

  grafana:
    image: logs-web
    container_name: grafana
    pull_policy: never
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs-web.entrypoints=http"
      - "traefik.http.routers.logs-web.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.entrypoints=https"
      - "traefik.http.routers.logs-web-secure.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.tls=true"
      - "traefik.http.routers.logs-web-secure.service=logs-web-secure"
      - "traefik.http.services.logs-web-secure.loadbalancer.server.port=3000"
      - "traefik.docker.network=external-sol-apis"
    depends_on:
      - loki
    networks:
      - logging-network
      - external-sol-apis
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=grafana,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 100M

volumes:
  grafana-data:

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
