version: '3.8'

services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    ports: []
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - logging

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/auto-deploy/logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - logging

  grafana:
    image: logs-web
    container_name: grafana
    pull_policy: never
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs-web.entrypoints=http"
      - "traefik.http.routers.logs-web.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.entrypoints=https"
      - "traefik.http.routers.logs-web-secure.rule=Host(`log.thiagosol.com`)"
      - "traefik.http.routers.logs-web-secure.tls=true"
      - "traefik.http.routers.logs-web-secure.service=logs-web-secure"
      - "traefik.http.services.logs-web-secure.loadbalancer.server.port=3000"
      - "traefik.docker.network=external-sol-apis"
    depends_on:
      - loki
    deploy:
      resources:
        limits:
          memory: 100M
    networks:
      - logging 
      - external-sol-apis

volumes:
  grafana-data:

networks:
  logging:
    driver: bridge
  external-sol-apis:
    external: true
