auth_enabled: false

server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
