server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "deploy-sh"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "deploy-sh"         
          service: "deploy-api"  
          __path__: "/var/log/*.log"

    pipeline_stages:
      - regex:
          source: filename
          expression: "/var/log/(?P<type>[^/]+)\\.log$"

      - labels:
          type:
