server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "deploy-sh"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "deploy-sh"         
          service: "deploy-api"  
          __path__: "/var/log/*.log"

    pipeline_stages:
      - regex:
          source: filename
          expression: "/var/log/(?P<type>[^/]+)\\.log$"

      - labels:
          type:
    
  - job_name: "docker"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker"
          type: "container"
          __path__: "/var/lib/docker/containers/*/*.log"

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            container_id: id
            container_name: attrs.name
            container_image: attrs.image

      - labels:
          service: container_id  

      - match:
          selector: '{job="docker"}'
          stages:
            - regex:
                source: stream
                expression: "^(?P<filtered_stream>stdout|stderr)$"
            - labels:
                stream: filtered_stream
