global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [name]
        target_label: container_name

      - source_labels: [id]
        target_label: container_id
