server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "logs"
          __path__: "/var/log/**/*.log"

    relabel_configs:
      - source_labels: [__filename]
        target_label: filename

      # Captura arquivos na raiz e define service = nome do arquivo e log = deploy
      - source_labels: [__filename]
        regex: ".*/([^/]+)\\.log$"
        replacement: "$1"
        target_label: service

      - source_labels: [__filename]
        regex: ".*/([^/]+)\\.log$"
        replacement: "deploy"
        target_label: log

      # Captura arquivos dentro de pastas e define service = nome da pasta e log = nome do arquivo
      - source_labels: [__filename]
        regex: ".*/([^/]+)/([^/]+)\\.log$"
        replacement: "$1"
        target_label: service

      - source_labels: [__filename]
        regex: ".*/([^/]+)/([^/]+)\\.log$"
        replacement: "$2"
        target_label: log
